# Generated by Django 3.2.7 on 2021-12-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_town', models.CharField(max_length=50)),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PointsTownsBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('id_point_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.pointstown')),
                ('id_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town')),
            ],
        ),
    ]
