# Generated by Django 3.2.7 on 2022-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='iron',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='town',
            name='stone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='town',
            name='wood',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
