# Generated by Django 3.2.7 on 2021-11-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towns',
            old_name='name_building',
            new_name='name_town',
        ),
    ]
