# Generated by Django 3.2.9 on 2021-12-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20211208_1844'),
        ('towns', '0002_rename_name_building_towns_name_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTownsBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('id_point_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.pointstown')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_town', models.CharField(max_length=50)),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PointsTownsBuildings',
        ),
        migrations.DeleteModel(
            name='Towns',
        ),
        migrations.AddField(
            model_name='pointstownsbuilding',
            name='id_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.town'),
        ),
    ]
