# Generated by Django 3.2.9 on 2021-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=255, verbose_name='Nickname')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
