# Generated by Django 3.2.9 on 2021-12-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_building', models.CharField(max_length=30)),
                ('building_level', models.PositiveSmallIntegerField()),
                ('building_health', models.PositiveIntegerField()),
                ('stone', models.PositiveSmallIntegerField()),
                ('wood', models.PositiveSmallIntegerField()),
                ('iron', models.PositiveSmallIntegerField()),
                ('size_warehouse', models.PositiveIntegerField(null=True)),
                ('id_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.unit')),
            ],
        ),
    ]
