# Generated by Django 3.2.9 on 2021-12-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_auto_20211208_1844'),
        ('buildings', '0002_auto_20211208_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buildings',
        ),
        migrations.AddField(
            model_name='building',
            name='id_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.units'),
        ),
    ]
